language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
after_script:
  - ./node_modules/.bin/now-travis
env:
  global:
  - secure: SXg/H4wXwCmKi56ZNd8BzhDZEX9QV9mXKQ7k/2AJ90on9LeSevzPq8ibw0F6KUx3q1d2N3Y+P0dQXgNAQ4I1ovo8W4uJYyigH1LQVfvkfeLkO6hwEh3GZJT+y8Vl84F/a3guWtVBd8wiJFzGjBzbu4bcS3ZuCeEAPcYq/EvguA1ptdlFAxQM7UmoBdTX72Fag28tcVLzqxsrXtqfUq+A8QVh7mlL0aQ0qkkkdJRCe6ETWmnH9X4QZgPYW7h4FRcUfFIGYwGkszMF4tqhw7YDAjKRBOUsyA4EJUiirmCWQISdUPwCa3GM2S7J/ReO6BT/VEZJCf/fOyxqTnI27Tt+5Sb0KR02K2HBfvzOPbrnh0PXkLK1PXCexwla+i7CV5jARcbvgxcEJMNzFwRRb27PHkAuhxhj2luypVD/wyZH2jJ7qMF1ovd0e0Sy0oDfeEYQXqlly9Sxtmpy45R0gL/M356cT8zq7LzTJkASdzDJVcLJ3hutl1gCs8SY5t1Wp6qRG6dBDF5pusT7mX0AiIbt60Qx0CAc0pOEIqjO3oEhA+7UDrIKwcZNpd03uC9CPVIb1emcPjbxIw1tNYc+mr/UfoRELXN6Yidmq3wbpA8EzceNZ1sxjbnwqoF11FRirzTu3fswDEe0QixOLFT38LK5V+QAEaC6JslJeWT/fmgkuVw=
  - secure: AUx0707Hcr+U6BoQlEU9xF0bWvULavkZM3/fpDnOU1Pxmvu7r2NKijHS073XWM7UqMliu3bl+LPpsvG8SQaPmrNp4ELVY05stM5Nz6zjGJ7iR+ZueXNg5JQll5BHtWxy4qavRNs+DRbwuJgC1W0gjF+NOOR9ESDuHxxDYkTnWayiqkSjTKjR4TYmjGdR+7cvZtB8feNpRgc/M3bHVLkOU0dFM2Xp3FLYX5tb2NKmok/3lZj/V035WPPseQ5c8TZuEwptTX2R7LUG12BGGsFyl5ehvd+x+rtsH34470iCMu9m76Ki4wnAU2Y4qTodyWUSuHEO7VIkNNGaAmSwTFYfmQ+OnVwQHoZnEC1fsKxm3GtHWOAa2Yq8EJofCMIAx4NbbdWHVeNWwipG/i9odN1SBOaEItKbMZpsuRJyK/9VjHSkOlaVAw2dy6UnaINlFiqwI0J4jbYgwVpur6G/5HGB1BxkTXD0XrCNLCvEYSghVwocGEvpDlq8yFzt+Gp5f6T3uxIEf/NUbUEHMK4qUDIgO9EeneSK2MB/ammoiFWSVvUGThyQlUgAsAM67uhIrfKt89NjmQEw7Z2FhWo84ngYgzrLwx/PrskV9r9/vz7wr6bP1bsPf7FkQsQ+voQ0yIOe5xECGjN5moooEb2bkRS3muuF5vCqqHfz/ahhq+Sjsvc=
